ALTER TABLE shipcore.fc_stats
  ADD COLUMN IF NOT EXISTS fba_90d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_60d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_30d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_15d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_7d_sales  NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_30d_pre   NUMERIC(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE shipcore.fc_stats_custom
  ADD COLUMN IF NOT EXISTS fba_90d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_60d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_30d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_15d_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_7d_sales  NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fba_30d_pre   NUMERIC(10, 2) NOT NULL DEFAULT 0;
