CREATE TABLE shipcore.fc_seat_cover_parts_third (
  id                          TEXT        NOT NULL DEFAULT gen_random_uuid()::TEXT,
  size                        TEXT        NOT NULL,
  inventory                   TEXT,
  fitting_photo               TEXT,
  confirmed                   TEXT,
  blueprint                   TEXT,
  manual                      TEXT,
  ymm                         TEXT,
  package                     TEXT,
  headrest                    TEXT,
  headrest_dp_detail          TEXT,
  headrest_qty                TEXT,
  headrest2                   TEXT,
  headrest2_dp_detail         TEXT,
  headrest2_qty               TEXT,
  top_body                    TEXT,
  top_body_dp_detail          TEXT,
  top_body_qty                TEXT,
  top_body2                   TEXT,
  top_body2_dp_detail         TEXT,
  top_body2_qty               TEXT,
  bottom                      TEXT,
  bottom_dp_detail            TEXT,
  bottom_qty                  TEXT,
  bottom2                     TEXT,
  bottom2_dp_detail           TEXT,
  bottom2_qty                 TEXT,
  middle_headrest             TEXT,
  middle_headrest_detail      TEXT,
  middle_headrest_qty         TEXT,
  middle_top_body             TEXT,
  middle_top_body_detail      TEXT,
  middle_top_body_qty         TEXT,
  middle_bottom               TEXT,
  middle_bottom_detail        TEXT,
  middle_bottom_qty           TEXT,
  console                     TEXT,
  console_dp_detail           TEXT,
  console_qty                 TEXT,
  backrest_storage            TEXT,
  backrest_storage_dp_detail  TEXT,
  backrest_storage_qty        TEXT,
  backrest_storage2           TEXT,
  backrest_storage2_dp_detail TEXT,
  backrest_storage2_qty       TEXT,
  armrest                     TEXT,
  armrest_detail              TEXT,
  armrest_qty                 TEXT,
  armrest2                    TEXT,
  armrest2_detail             TEXT,
  armrest2_qty                TEXT,
  subpart                     TEXT,
  subpart_dp_detail           TEXT,
  subpart_qty                 TEXT,
  subpart2                    TEXT,
  subpart2_dp_detail          TEXT,
  subpart2_qty                TEXT,
  note                        TEXT,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fc_seat_cover_parts_third_pkey PRIMARY KEY (id),
  CONSTRAINT fc_seat_cover_parts_third_size_key UNIQUE (size)
);
