name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/coverland/app
            git fetch origin
            git checkout main
            git reset --hard origin/main
            npm install
            npx prisma migrate deploy
            npx prisma generate
            npm run build
            pm2 restart demand-pilot
